import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { BsApple, BsGithub, BsLinkedin, BsYoutube,BsSpotify } from 'react-icons/bs'
import { SiLeetcode } from 'react-icons/si'
import { CgUserlane } from 'react-icons/cg'
import { SiHackerrank } from 'react-icons/si'

import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>LinkTree | Vishek Patel</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className='flex flex-col items-center gap-2'>

      <h1 className="text-6xl font-bold mb-8 bg-clip-text text-transparent bg-gradient-to-r from-blue-500 to-indigo-600">
      LinkTree
    </h1>

    <Link href="https://www.linkedin.com/in/imvishek/">
    <div className='p-4 flex justify-between items-center w-80 md:w-96 h-20 border border-blue-600 rounded-md cursor-pointer mb-2 hover:scale-105 transistion duration-150 ease-in-out' >
    <BsLinkedin className='text-5xl text-white'/>
    <span className='text-2xl font-bold text-blue-600'>Linkedin</span>
    </div>
    </Link>

    <Link href="https://github.com/vishek-patel">
    <div className='p-4 flex justify-between items-center w-80 md:w-96 h-20 border border-blue-600 rounded-md cursor-pointer mb-2 hover:scale-105 transistion duration-150 ease-in-out'>
    <BsGithub className='text-5xl text-white'/>
    <span className='text-2xl font-bold text-blue-600'>Github</span>
    </div>
    </Link>

    <Link href="https://leetcode.com/">
    <div className='p-4 flex justify-between items-center w-80 md:w-96 h-20 border border-blue-600 rounded-md cursor-pointer mb-2 hover:scale-105 transistion duration-150 ease-in-out'>    
    <SiLeetcode className='text-5xl text-white'/>
    <span className='text-2xl font-bold text-blue-600'>Leetcode</span>
    </div>
    </Link>

    <Link href="https://www.hackerrank.com/vishekpatel033">
    <div className='p-4 flex justify-between items-center w-80 md:w-96 h-20 border border-blue-600 rounded-md cursor-pointer mb-2 hover:scale-105 transistion duration-150 ease-in-out'>
    <SiHackerrank className='text-5xl text-white'/>
    <span className='text-2xl font-bold text-blue-600'>Hackerrank</span>
    </div>
    </Link>

    <Link href="https://open.spotify.com/user/yz4kljnlep9shhiz17kd89b17">
    <div className='p-4 flex justify-between items-center w-80 md:w-96 h-20 border border-blue-600 rounded-md cursor-pointer mb-2 hover:scale-105 transistion duration-150 ease-in-out'> 
    <BsSpotify className='text-5xl text-white'/>
    <span className='text-2xl font-bold text-blue-600'>Spotify</span>
    </div>
    </Link>


    <Link href="https://vishek-patel-portfolio.netlify.app/">
    <div className='p-4 flex justify-between items-center w-80 md:w-96 h-20 border border-blue-600 rounded-md cursor-pointer mb-2 hover:scale-105 transistion duration-150 ease-in-out'> 
    <CgUserlane className='text-5xl text-white'/>
    <span className='text-2xl font-bold text-blue-600'>Portfolio</span>
    </div>
    </Link>
        
    </div>
      </main>
    </>
  )
}
